sudo: required

language: go
go:
  - 1.9

services:
  - docker

script:
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bot *.go

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - export REPO=$DOCKER_USER/bot
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker push $REPO
